print('Hello World!')
print('Hello World!! Again!!!!')
print("I became expert in python after typing this.")
print("Python is fun.")
print("Everything I am typing is printing.")
print("I'd like to show my 'coding' skills to 'mark'.")
print('I"d like to show my "coding" skills to "mark".')
print('I became \'best\' coder by printing "previous" line.')
print("""I became 'best' coder by printing "previous" line.""")

print(__name__)